services:
  web:
    build: .
    command: bash -lc "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn toir_project.wsgi:application --bind 0.0.0.0:8000 --workers 3 --reload"
    env_file: .env
    expose:
      - "8000"
    depends_on: [db, redis]
    volumes:
      - .:/app
      - static:/app/staticfiles
      - media:/app/media
    # Добавьте эти строки для разработки
    environment:
      - PYTHONUNBUFFERED=1
      - DEBUG=True

  worker:
    build: .
    command: celery -A toir_project worker -l info
    env_file: .env
    depends_on: [db, redis]
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DEBUG=True

  beat:
    build: .
    command: celery -A toir_project beat -l info
    env_file: .env
    depends_on: [db, redis]
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DEBUG=True

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - static:/app/staticfiles
      - media:/app/media

volumes:
  pgdata:
  static:
  media: